# Generated by Django 2.2.12 on 2024-07-09 11:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_II_survey_da', '0004_auto_20240709_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='abi_grade',
            field=otree.db.models.FloatField(null=True, verbose_name='Welche Note haben Sie in Ihrem höchsten Schulabschluss erzielt (z.B. Abitur, Mittlere Reife, ...)?'),
        ),
    ]
