# Generated by Django 2.2.12 on 2024-07-15 16:38

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_ii_survey_da4_group', to='otree.Session')),
            ],
            options={
                'db_table': 'part_II_survey_da4_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_ii_survey_da4_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'part_II_survey_da4_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='2€')),
                ('q2', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='3€')),
                ('q3', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='4€')),
                ('q4', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='5€')),
                ('q5', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='6€')),
                ('q6', otree.db.models.IntegerField(choices=[(0, 'Ich möchte die Münze nicht werfen'), (1, 'Ich möchte die Münze werfen')], null=True, verbose_name='7€')),
                ('pref_decision', otree.db.models.LongStringField(null=True, verbose_name='Wie haben Sie Ihre Entscheidung über die Präferenzlisten getroffen?')),
                ('truth_telling_decision', otree.db.models.BooleanField(choices=[[True, 'Ja, ich habe meine Präferenzlisten so erstellt, dass sie der Reihenfolge der Werte aus der Wertetabelle entsprachen.'], [False, 'Nein, ich habe meine Präferenzlisten nicht so erstellt.']], null=True, verbose_name='Haben Sie Ihre Präferenzlisten meistens oder immer so erstellt, dass sie der Reihenfolge der Werte aus der Wertetabelle entsprachen?')),
                ('explanation_tt_yes', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Warum haben Sie Ihre Präferenzliste so erstellt, dass Sie der Reihenfolge der Werte aus der Wertetabelle entsprachen?')),
                ('explanation_tt_no', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Warum haben Sie Ihre Präferenzliste nicht so erstellt, dass Sie der Reihenfolge der Werte aus der Wertetabelle entsprachen?')),
                ('mechanism_fair', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für fair?')),
                ('mechanism_efficient', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für effizient?')),
                ('mechanism_comprehensive', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für verständlich?')),
                ('trust_general', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Solange ich nicht vom Gegenteil überzeugt bin, gehe ich davon aus, dass Menschen nur die besten\n        Absichten haben.')),
                ('trust_mechanism', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Ich bin davon überzeugt, dass das Zulassungsverfahren aus dem ersten Teil gut funktioniert.')),
                ('trust_institutions_gvmnt', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in die Regierung.')),
                ('trust_institutions_city', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in städtischen Behörden.')),
                ('trust_institutions_educ', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in Bildungsbehörden.')),
                ('crt_bat', otree.db.models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ein Schläger und ein Ball kosten insgesamt 1,10 €. Der Schläger kostet 1 € mehr als der Ball. Wie viel kostet der Ball?')),
                ('crt_widget', otree.db.models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Wenn 5 Maschinen 5 Minuten brauchen um 5 Produkte herzustellen, wie lange benötigen dann 100 Maschinen, um 100 Produkte herzustellen?')),
                ('crt_lake', otree.db.models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='In einem See wachsen Seerosen, die sich jeden Tag verdoppeln. Wenn es 48 Tage dauert, bis der ganze See bedeckt ist, wie lange dauert es, bis die Seerosen die Hälfte des Sees bedecken?')),
                ('gender', otree.db.models.StringField(choices=[['female', 'Weiblich'], ['male', 'Männlich'], ['diverse', 'Divers'], ['no_gender', 'Ich identifiziere mich mit keinem Geschlecht']], max_length=10000, null=True, verbose_name='Mit welchem Geschlecht identifizieren Sie sich?')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Wie alt sind Sie?')),
                ('studying_currently', otree.db.models.StringField(choices=[['1 - currently student', 'Ich studiere derzeit.'], ['2 - currently doctoral student', 'Ich promoviere.'], ['3 - has graduated from university', 'Ich habe ein Studium abgeschlossen.'], ['0 - no university education', 'Nein.']], max_length=10000, null=True, verbose_name='Studieren Sie derzeit oder haben Sie ein Studium abgeschlossen?')),
                ('study_field', otree.db.models.StringField(blank=True, choices=[['Humanities', 'Geisteswissenschaften (z.\u202fB. Sprachen, Medienwissenschaften, Philosophie, Kunstgeschichte)'], ['Art and music', 'Kunst und Musik'], ['Mathematics', 'Mathematik, Informatik, Technik oder Ingenieurwissenschaften'], ['Natural sciences', 'Naturwissenschaften (z.\u202fB. Biologie, Chemie, Physik, Agrarwissenschaften)'], ['Medicine', 'Medizin'], ['Psychology', 'Psychologie'], ['Law', 'Rechtswissenschaft'], ['Social sciences', 'Sozial- oder Kulturwissenschaften (inkl. z.\u202fB. Politikwissenschaft, Anthropologie, Geschichte)'], ['Economic sciences', 'Wirtschaftswissenschaften (BWL, VWL, Wirtschaftsingenieurwesen, Wirtschaftsmathematik)'], ['Other', 'Anderer Studiengang']], max_length=10000, null=True, verbose_name='In welchem Studiengang studieren Sie bzw. haben Sie studiert?')),
                ('current_occupation', otree.db.models.StringField(blank=True, choices=[['Occupied', 'Ich bin erwerbstätig.'], ['Jobless', 'Ich bin arbeitslos.'], ['Retired', 'Ich bin im Ruhestand.'], ['Parental leave', 'Ich befinde mich in Elternzeit.'], ['Student', 'Ich studiere.'], ['Apprentice', 'Ich absolviere eine Ausbildung.'], ['Sabbatical', 'Ich mache ein Sabbatical.'], ['Other', 'Sonstiges.']], max_length=10000, null=True, verbose_name='Welcher Beschäftigung gehen Sie derzeit nach?')),
                ('semester', otree.db.models.StringField(blank=True, choices=[['semester_1', '1. Fachsemester'], ['semester_2', '2. Fachsemester'], ['semester_3', '3. Fachsemester'], ['semester_4', '4. Fachsemester'], ['semester_5', '5. Fachsemester'], ['semester_6', '6. Fachsemester'], ['semester_7', '7. Fachsemester'], ['semester_8', '8. Fachsemester'], ['semester_9', '9. Fachsemester'], ['semester_10', '10. Fachsemester'], ['semester_11', '11. Fachsemester'], ['semester_12', '12. Fachsemester'], ['semester_13', '13. Fachsemester'], ['semester_14', '14. Fachsemester'], ['semester_15', '15. Fachsemester'], ['semester_16', '16. Fachsemester'], ['semester_17', '17. Fachsemester'], ['semester_18', '18. Fachsemester'], ['semester_19', '19. Fachsemester'], ['semester_20', '20. Fachsemester']], max_length=10000, null=True, verbose_name='In welchem Fachsemester sind Sie eingeschrieben?')),
                ('math_grade', otree.db.models.FloatField(null=True, verbose_name='Was war Ihre letzte Mathenote?')),
                ('abi_grade', otree.db.models.FloatField(null=True, verbose_name='Welche Note haben Sie in Ihrem höchsten Schulabschluss erzielt (z.B. Abitur, Mittlere Reife, ...)?')),
                ('risk', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n        Wie nehmen Sie sich selbst wahr? \n        Sind Sie generell ein Mensch, der voll und ganz bereit ist, Risiken einzugehen, oder versuchen Sie eher, Risiken zu vermeiden?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part_II_survey_da4.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_ii_survey_da4_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_ii_survey_da4_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_II_survey_da4.Subsession')),
            ],
            options={
                'db_table': 'part_II_survey_da4_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_II_survey_da4.Subsession'),
        ),
    ]
