# Generated by Django 2.2.12 on 2024-07-09 11:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_II_survey_ttc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='crt_bat',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Ein Schläger und ein Ball kosten insgesamt 1,10€. Der Schläger kostet 1€ mehr als der Ball. Wie viel kostet der Ball?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='crt_lake',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='In einem See wachsen Seerosen, die sich jeden Tag verdoppeln. Wenn es 48 Tage dauert, bis der ganze See bedeckt ist, wie lange dauert es, bis die Seerosen die Hälfte des Sees bedecken?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='crt_widget',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Wenn 5 Maschinen 5 Minuten brauchen um 5 Produkte herzustellen, wie lange benötigen dann 100 Maschinen, um 100 Produkte herzustellen?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mechanism_comprehensive',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für verständlich?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mechanism_efficient',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für effizient?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mechanism_fair',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='... für fair?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pref_decision',
            field=otree.db.models.LongStringField(null=True, verbose_name='Wie haben Sie Ihre Entscheidung über die Präferenzlisten getroffen?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trust_general',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Solange ich nicht vom Gegenteil überzeugt bin, gehe ich davon aus, dass Menschen nur die besten\n        Absichten haben.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trust_institutions_city',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in städtischen Behörden.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trust_institutions_educ',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in Bildungsbehörden.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trust_institutions_gvmnt',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Im Allgemeinen habe ich Vertrauen in die Regierung.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trust_mechanism',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Ich bin davon überzeugt, dass das Zulassungsverfahren aus dem ersten Teil gut funktioniert.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='truth_telling_decision',
            field=otree.db.models.BooleanField(choices=[[True, 'Ja, ich habe meine Präferenzlisten so erstellt, dass sie der Reihenfolge der Werte aus der Wertetabelle entsprachen.'], [False, 'Nein, ich habe meine Präferenzlisten nicht so erstellt.']], null=True, verbose_name='Haben Sie Ihre Präferenzlisten meistens oder immer so erstellt, dass sie der Reihenfolge der Werte aus der Wertetabelle entsprachen?'),
        ),
    ]
