# Generated by Django 2.2.12 on 2024-07-10 19:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_II_survey_ttc', '0008_auto_20240709_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='crt_bat',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Ein Schläger und ein Ball kosten insgesamt 1,10 €. Der Schläger kostet 1 € mehr als der Ball. Wie viel kostet der Ball?'),
        ),
    ]
