# Generated by Django 2.2.12 on 2024-07-09 09:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_I_da', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ctrq2_da',
            field=otree.db.models.IntegerField(null=True, verbose_name='2. Wie viele Plätze bleiben übrig, sobald alle Schüler:innen an einer Schule zugelassen wurden?'),
        ),
    ]
