# Generated by Django 2.2.12 on 2024-07-09 11:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_I_ttc', '0002_auto_20240709_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ctrq1_ttc',
            field=otree.db.models.IntegerField(null=True, verbose_name='Wie viele Schüler:innen bewerben sich für einen Schulplatz?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ctrq2_ttc',
            field=otree.db.models.IntegerField(null=True, verbose_name='Wie viele Plätze bleiben übrig, sobald alle Schüler:innen an einer Schule zugelassen wurden?'),
        ),
    ]
